name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .ssh directory and set permissions
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Decode SSH key and set permissions
      run: |
        echo "$SSH_KEY" | base64 --decode > ~/.ssh/jihuncha.pem
        chmod 600 ~/.ssh/jihuncha.pem

    # 종속성 설치 (npm install)
    - name: Install dependencies
      working-directory: ./frontend
      run: npm install

    # 실행 권한 부여
    - name: Set executable permissions for react-scripts
      working-directory: ./frontend
      run: chmod +x ./node_modules/.bin/react-scripts

    # 빌드 과정 추가
    - name: Build the project
      working-directory: ./frontend
      run: npm run build

    # Add EC2 to known hosts
    - name: Add EC2 to known hosts
      run: ssh-keyscan -H 54.159.220.38 >> ~/.ssh/known_hosts

    # 배포 및 Nginx 재시작
    - name: Deploy to EC2
      run: |
        set -e  # 에러 발생 시 스크립트 종료
        scp -i ~/.ssh/jihuncha.pem -r ./frontend/build/* ec2-user@54.159.220.38:/var/www/html/
        ssh -i ~/.ssh/jihuncha.pem ec2-user@54.159.220.38 "sudo systemctl restart nginx"
